#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          networking ifupdown
# Required-Start:    mountkernfs $local_fs urandom
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Raise network interfaces.
# Description:       Prepare /run/network directory, ifstate file and raise network interfaces, or take them down.
### END INIT INFO

# Copied from https://github.com/ifupdown-ng/ifupdown-ng/blob/main/dist/debian/networking
#
# Wrapper script for networking set up and teardown via unit file
#
# Thu, 01 Oct 2020 22:47:43 +0200
#  -- Maximilian Wilhelm <max@sdn.clinic>
#

STATE_DIR="/run/ifsate"

# Make sure the state dir is present
if [ ! -d "${STATE_DIR}" ]; then
        mkdir "${STATE_DIR}"
fi

# Check for require binaries
if [ ! -x /sbin/ifup -o ! -x /sbin/ifdown ]; then
        echo "ifup and/or ifdown not found!" >&2
        exit 1
fi

# Apply defaults if present (verbose mode, kill switch, etc.)
CONFIGURE_INTERFACES=yes

if [ -f /etc/default/networking ]; then
        . /etc/default/networking
fi

ARGS=""
if [ "${VERBOSE}" = yes ]; then
        ARGS="-v"
fi

# Let's go
case "$1" in
        start)
                if [ "${CONFIGURE_INTERFACES}" = no ]; then
                        echo "Not configuring network interfaces, see /etc/default/networking"
                        exit 0
                fi

                ifup -a ${ARGS}
                ;;

        stop)
                ifdown -a ${ARGS}
                ;;

        restart)
                ifupdown_init
                ifdown -a ${ARGS}
                ifup -a ${ARGS}
                ;;

        # reload missing here!

        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac

exit 0
